name: Teste da API
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # - name: Executar API
      #   run: |
      #     python -m flask --app app run

      - name: Executar Testes
        run: |
          pytest
